"""Builds the static GitHub Pages demo (docs/demo/) from demo-vault/.

The demo is the real frontend (frontend/) plus docs/demo/demo-api.js, which answers the app's /api/* calls
in the browser from a precomputed snapshot (docs/demo/data.js). AI answers there are scripted — GitHub Pages
has no server and no model.

Run from the project root:  python scripts/build_demo.py
"""
import datetime as dt
import hashlib
import json
import os
import shutil
import sys
import tempfile
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT))

from backend.cloud import PRESETS  # noqa: E402
from backend.templates import Templates  # noqa: E402
from backend.vault import Vault  # noqa: E402

VAULT = ROOT / "demo-vault"
FRONTEND = ROOT / "frontend"
OUT = ROOT / "docs" / "demo"
BUILD_DAY = dt.datetime(2026, 9, 26, 12, 0)  # fixed "today" so rebuilding gives the same demo

BANNER = """<div class="demo-banner">
  <b>Демо Mnemo</b> на примере хранилища · ИИ заменён заготовленными ответами, изменения не сохраняются
  <a href="../" target="_top">← О проекте</a>
</div>
"""


def set_demo_mtimes(vault: Vault):
    """Git doesn't keep file times: derive a plausible 'last modified' from each note's creation date."""
    for rel, note in vault.notes.items():
        seed = int(hashlib.md5(rel.encode("utf-8")).hexdigest(), 16)
        created = dt.datetime.fromtimestamp(note.created)
        modified = min(created + dt.timedelta(days=seed % 60, hours=seed % 11), BUILD_DAY)
        ts = modified.timestamp()
        os.utime(vault.safe_path(rel), (ts, ts))


def main():
    with tempfile.TemporaryDirectory() as tmp:
        vault = Vault(str(VAULT), Path(tmp))
        templates = Templates(vault.root)
        vault.exclude_folders = {templates.folder.lower()} if templates.folder else set()
        vault.scan(force=True)
        set_demo_mtimes(vault)
        vault.scan(force=True)

        data = {
            "vault": vault.name,
            "built": BUILD_DAY.isoformat(),
            "stats": vault.stats(),
            "graph": vault.graph(),
            "folders": vault.folders,
            "list": vault.list_notes(),
            "notes": {p: vault.note_details(p) for p in sorted(vault.notes)},
            "templates": {"folder": templates.folder, "folder_map": templates.folder_map, "items": templates.list()},
            "template_sources": {t["name"]: (vault.root / t["path"]).read_text(encoding="utf-8") for t in templates.list()},
            "presets": PRESETS,
        }

    OUT.mkdir(parents=True, exist_ok=True)
    (OUT / "data.js").write_text(
        "// Generated by scripts/build_demo.py from demo-vault/ — do not edit by hand.\n"
        "window.MNEMO_DEMO = " + json.dumps(data, ensure_ascii=False) + ";\n", encoding="utf-8")

    for name in ("app.js", "style.css"):
        shutil.copy2(FRONTEND / name, OUT / name)
    shutil.copytree(FRONTEND / "vendor", OUT / "vendor", dirs_exist_ok=True)

    html = (FRONTEND / "index.html").read_text(encoding="utf-8")
    html = html.replace('"/static/', '"')  # GitHub Pages serves the demo from a sub-path
    html = html.replace('<script src="app.js"></script>',
                        '<script src="data.js"></script>\n<script src="demo-api.js"></script>\n<script src="app.js"></script>')
    html = html.replace('<link rel="stylesheet" href="style.css">',
                        '<link rel="stylesheet" href="style.css">\n  <link rel="stylesheet" href="demo.css">')
    html = html.replace("<title>Mnemo</title>", "<title>Mnemo — демо</title>")
    html = html.replace("<body>\n", "<body class=\"demo\">\n" + BANNER, 1)
    assert "demo-api.js" in html and "demo-banner" in html, "frontend/index.html layout changed — update build_demo.py"
    (OUT / "index.html").write_text(html, encoding="utf-8")

    n = len(data["notes"])
    size = (OUT / "data.js").stat().st_size // 1024
    print(f"demo built: {n} notes, data.js {size} KB -> {OUT}")


if __name__ == "__main__":
    main()
